version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - bodyclose
    - dogsled
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - hugeParam # Label types are value types by design
        - ifElseChain # Sometimes if-else is clearer than switch
        - appendAssign # Intentional slice copy pattern
    gocyclo:
      min-complexity: 30 # Parser functions are inherently complex
    govet:
      enable:
        - shadow
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - gocritic
          - gosec
          - mnd
          - funlen
          - goconst
          - gocyclo
          - unparam
        path: _test\.go
      - linters:
          - errcheck
          - gocritic
          - gosec
          - mnd
          - funlen
          - goconst
          - gocyclo
          - unparam
        path: e2e/
      - linters:
          - gosec
        text: "G304" # File inclusion via variable is fine for parser
      - linters:
          - mnd
        path: ast/ # Parser index checks are self-explanatory
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
