package lockfile

import (
	"encoding/json"
)

// CurrentVersion is the lockfile format version this package targets.
// This corresponds to Bazel 9.0.0 lockfile format.
// See version.go for the complete Bazel-to-lockfile version mapping.
const CurrentVersion = 26

// Lockfile represents a MODULE.bazel.lock file.
// This matches Bazel's BazelLockFileValue structure.
type Lockfile struct {
	// Version is the lockfile format version.
	Version int `json:"lockFileVersion"`

	// RegistryFileHashes maps registry URLs to their content hashes.
	// Keys are full URLs like "https://bcr.bazel.build/modules/foo/1.0/MODULE.bazel".
	// Values are SHA256 hashes of the file contents. A nil value means the file
	// was probed but not found, matching Bazel's lockfile semantics.
	RegistryFileHashes map[string]*string `json:"registryFileHashes"`

	// SelectedYankedVersions maps ModuleKey strings to yank reasons.
	// These are yanked versions that were explicitly allowed.
	SelectedYankedVersions map[string]string `json:"selectedYankedVersions"`

	// ModuleExtensions contains cached results of module extension evaluations.
	// Keys are extension identifiers like "@@rules_go+//go:extensions.bzl%go_sdk".
	ModuleExtensions map[string]ModuleExtensionEntry `json:"moduleExtensions"`

	// Facts contains additional facts about module extensions.
	Facts map[string]json.RawMessage `json:"facts"`
}

// ModuleExtensionEntry contains evaluation results for a module
// extension. The outer map key on Lockfile.ModuleExtensions is the
// extension ID; this inner map's key is the scope —
// either "general" (platform-independent extensions) or an
// "<os>_<arch>" string (extensions marked os_dependent / arch_dependent).
type ModuleExtensionEntry map[string]ModuleExtensionData

// ModuleExtensionData captures one (extension, scope)'s evaluation
// state. Field set verified against real Bazel-emitted lockfiles
// spanning v13 - v26 (see realcorpus_test.go).
//
// Note: the JSON value under each scope key IS this struct directly —
// there is no second "general" wrapper. An earlier version of this
// model expected one, which made every field below silently zero on
// real lockfiles. See testdata/README.md for the corpus that pinned
// the correct shape.
type ModuleExtensionData struct {
	// BzlTransitiveDigest is a hash of the extension's transitive .bzl files.
	BzlTransitiveDigest string `json:"bzlTransitiveDigest,omitempty"`

	// UsagesDigest is a hash of how the extension is used.
	UsagesDigest string `json:"usagesDigest,omitempty"`

	// GeneratedRepoSpecs contains the repositories generated by the
	// extension. Keyed by canonical repo name.
	GeneratedRepoSpecs map[string]RepoSpec `json:"generatedRepoSpecs,omitempty"`

	// RecordedRepoMappingEntries records the repo-mapping entries the
	// extension's eval observed. Bazel emits this as a list of [from,
	// to] pairs (each itself a list) — leave it untyped to survive
	// schema evolution; consumers that need it can type-assert.
	RecordedRepoMappingEntries any `json:"recordedRepoMappingEntries,omitempty"`

	// RecordedFileInputs and RecordedDirentsInputs record per-file
	// digests and per-directory entry sets observed during eval. Keys
	// are workspace-relative paths; values vary by schema version.
	RecordedFileInputs    map[string]string `json:"recordedFileInputs,omitempty"`
	RecordedDirentsInputs map[string]any    `json:"recordedDirentsInputs,omitempty"`

	// EnvVariables records the values of environment variables the
	// extension's eval depended on (extension(environ=[...]) at
	// declaration time). Keyed by env var name.
	EnvVariables map[string]string `json:"envVariables,omitempty"`
}

// RepoSpec describes a repository generated by a module extension.
//
// The identity representation differs across lockfile versions:
//   - v13/v14 emit BzlFile (canonical .bzl label) + RuleClassName
//     (rule name) as separate fields.
//   - v18+ consolidates them into RepoRuleID of the form
//     "<BzlFile>%<RuleClassName>".
//
// Both representations are preserved on parse; Parse() also fills
// RepoRuleID from BzlFile/RuleClassName when the file used the
// older schema, so consumers can rely on RepoRuleID being non-empty.
type RepoSpec struct {
	// RepoRuleID is the consolidated identifier
	// (e.g. "@@bazel_tools+//tools/build_defs/repo:http.bzl%http_archive").
	// v18+ schemas emit this directly; for v13/v14 lockfiles it's
	// synthesized post-parse from BzlFile + RuleClassName.
	RepoRuleID string `json:"repoRuleId,omitempty"`

	// BzlFile is the canonical label of the .bzl file declaring the
	// repo rule. Present in v13/v14 lockfiles; populated post-parse
	// from RepoRuleID in v18+ lockfiles.
	BzlFile string `json:"bzlFile,omitempty"`

	// RuleClassName is the bare rule symbol (e.g. "http_archive").
	// Present in v13/v14 lockfiles; populated post-parse from
	// RepoRuleID in v18+ lockfiles.
	RuleClassName string `json:"ruleClassName,omitempty"`

	// Attributes are the arguments passed to the repo rule.
	Attributes map[string]any `json:"attributes,omitempty"`
}

// ModuleKey represents a module name and version pair.
type ModuleKey struct {
	Name    string
	Version string
}

// String returns the string representation "name@version" or "name@_" for overrides.
func (k ModuleKey) String() string {
	if k.Version == "" {
		return k.Name + "@_"
	}
	return k.Name + "@" + k.Version
}

// MarshalText implements encoding.TextMarshaler for use as map keys.
func (k ModuleKey) MarshalText() ([]byte, error) {
	return []byte(k.String()), nil
}

// UnmarshalText implements encoding.TextUnmarshaler for use as map keys.
func (k *ModuleKey) UnmarshalText(text []byte) error {
	s := string(text)
	for i := len(s) - 1; i >= 0; i-- {
		if s[i] == '@' {
			k.Name = s[:i]
			k.Version = s[i+1:]
			if k.Version == "_" {
				k.Version = ""
			}
			return nil
		}
	}
	k.Name = s
	k.Version = ""
	return nil
}

// New creates a new empty lockfile with the current version.
func New() *Lockfile {
	return &Lockfile{
		Version:                CurrentVersion,
		RegistryFileHashes:     make(map[string]*string),
		SelectedYankedVersions: make(map[string]string),
		ModuleExtensions:       make(map[string]ModuleExtensionEntry),
		Facts:                  make(map[string]json.RawMessage),
	}
}

// SetRegistryHash records the hash for a registry file URL.
func (l *Lockfile) SetRegistryHash(url, hash string) {
	if l.RegistryFileHashes == nil {
		l.RegistryFileHashes = make(map[string]*string)
	}
	l.RegistryFileHashes[url] = stringPointer(hash)
}

// SetMissingRegistryHash records that a registry file URL was probed but not found.
func (l *Lockfile) SetMissingRegistryHash(url string) {
	if l.RegistryFileHashes == nil {
		l.RegistryFileHashes = make(map[string]*string)
	}
	l.RegistryFileHashes[url] = nil
}

// GetRegistryHash returns the recorded hash for a URL, or empty if not found.
// It also returns an empty string for recorded "not found" entries.
func (l *Lockfile) GetRegistryHash(url string) string {
	hash := l.RegistryFileHashes[url]
	if hash == nil {
		return ""
	}
	return *hash
}

// GetRegistryHashValue returns the raw recorded value for a URL.
// The bool reports whether the URL exists in the lockfile.
func (l *Lockfile) GetRegistryHashValue(url string) (*string, bool) {
	hash, ok := l.RegistryFileHashes[url]
	if !ok {
		return nil, false
	}
	return cloneStringPointer(hash), true
}

// HasRegistryHash returns true if a hash is recorded for the URL.
func (l *Lockfile) HasRegistryHash(url string) bool {
	_, ok := l.RegistryFileHashes[url]
	return ok
}

// IsRegistryHashMissing returns true if the URL is present and explicitly
// recorded as not found.
func (l *Lockfile) IsRegistryHashMissing(url string) bool {
	hash, ok := l.RegistryFileHashes[url]
	return ok && hash == nil
}

// AllowYankedVersion records that a yanked version was explicitly allowed.
func (l *Lockfile) AllowYankedVersion(key ModuleKey, reason string) {
	if l.SelectedYankedVersions == nil {
		l.SelectedYankedVersions = make(map[string]string)
	}
	l.SelectedYankedVersions[key.String()] = reason
}

// IsYankedVersionAllowed returns true if the yanked version is explicitly allowed.
func (l *Lockfile) IsYankedVersionAllowed(key ModuleKey) bool {
	_, ok := l.SelectedYankedVersions[key.String()]
	return ok
}

// GetYankedVersionReason returns the reason a yanked version was allowed.
func (l *Lockfile) GetYankedVersionReason(key ModuleKey) string {
	return l.SelectedYankedVersions[key.String()]
}

// RegistryURLs returns all registry URLs that have recorded hashes.
func (l *Lockfile) RegistryURLs() []string {
	urls := make([]string, 0, len(l.RegistryFileHashes))
	for url := range l.RegistryFileHashes {
		urls = append(urls, url)
	}
	return urls
}

func cloneStringPointer(s *string) *string {
	if s == nil {
		return nil
	}
	value := *s
	return &value
}

func stringPointer(s string) *string {
	value := s
	return &value
}

// ExtensionIDs returns all module extension identifiers in the lockfile.
func (l *Lockfile) ExtensionIDs() []string {
	ids := make([]string, 0, len(l.ModuleExtensions))
	for id := range l.ModuleExtensions {
		ids = append(ids, id)
	}
	return ids
}

// IsCompatible returns true if the lockfile version is compatible with this package.
// Note: Bazel itself requires EXACT version matching. This method is more lenient
// for reading/parsing purposes. Use IsExactMatch() for Bazel-compatible behavior.
func (l *Lockfile) IsCompatible() bool {
	// Allow reading lockfiles from Bazel 7.2.0+ (version 11+)
	// These share a similar structure with incremental lockfile format.
	return l.Version >= 11 && l.Version <= CurrentVersion+4
}

// IsExactMatch returns true if the lockfile version exactly matches CurrentVersion.
// This is what Bazel requires for lockfile compatibility.
func (l *Lockfile) IsExactMatch() bool {
	return l.Version == CurrentVersion
}

// RequiredBazelVersion returns the Bazel version(s) that use this lockfile version.
// Returns nil if the version is unknown.
func (l *Lockfile) RequiredBazelVersion() []BazelVersion {
	return BazelVersionsForLockfile(l.Version)
}
